var cartona = "<p>1. Nymphaea lotus (Egyptian Lotus) <br><br> The Nymphaea lotus, or Egyptian lotus, stands out as one of the most iconic plants in Egypt, revered for both its beauty and profound cultural symbolism. Found predominantly in calm aquatic environments such as rivers, shallow lakes, and swamps, where water movement is slow or still, the Egyptian lotus prefers warm temperatures and thrives in direct sunlight for extended periods. It requires water temperatures between 20-30°C for optimal growth. Egypt, with its ancient ties to the Nile, provides an ideal habitat for the lotus, where it flourishes in the country's warm climate. The Egyptian lotus is characterized by its large, flat, floating leaves and magnificent white or light pink flowers that exhibit a unique daily bloom cycle—opening at sunrise and closing at sunset. This cycle was seen as a representation of the sun’s journey and became a powerful symbol in ancient Egyptian mythology, where it was associated with creation, rebirth, and the cyclical nature of life itself. The lotus frequently appeared in temple art, tomb decorations, and hieroglyphics, signifying spiritual purity and the eternal cycle of the afterlife.Beyond its symbolic value, Nymphaea lotus plays an essential ecological role in maintaining the water temperature and providing food and shelter for fish, amphibians, and invertebrates. It also has medicinal properties, traditionally used for its sedative, anti-inflammatory effects, and as a treatment for stomach issues and respiratory problems. Additionally, its seeds and parts of the flower are consumed as food. Although the lotus is not globally endangered, it is increasingly vulnerable due to water pollution, aquatic plant removal, and changes in water levels, particularly in the Nile River lakes of Egypt and Sudan. Protecting aquatic environments from pollution and promoting sustainable agriculture are essential for ensuring the survival of this symbolically and ecologically significant species.</p>";
var cartona2 = "<p>Cyperus papyrus (Papyrus Plant) <br><br> The Cyperus papyrus plant has a legacy that stretches back thousands of years, playing a pivotal role in the development of human civilization, particularly in Egypt. Native to wetland environments, Cyperus papyrus thrives in areas along riverbanks and swamps where the soil remains partially submerged in water. It requires warm temperatures ranging from 20-35°C and large amounts of water to grow healthily. Ancient Egyptians discovered that the fibrous interior of the papyrus stalk could be processed into durable writing material, leading to the creation of papyrus paper. This discovery was monumental, allowing for the recording of sacred texts, letters, and artwork, which fundamentally shaped the growth of ancient Egyptian civilization. Papyrus was more than a writing material; it was integral to the trade and economy of Egypt, and its production influenced surrounding Mediterranean regions.Besides its historical significance, Cyperus papyrus plays an essential ecological role. The plant's hollow stalks, which can grow up to 5 meters tall, serve as natural water filters, trapping sediments and absorbing excess nutrients. Additionally, it provides a habitat for various bird, fish, and insect species, supporting biodiversity in wetlands. However, the presence of papyrus in the wild has significantly diminished due to the degradation of wetlands, drought, and land conversion for agriculture and urban use, particularly in the Nile Delta of Egypt and regions in East Africa. While not globally threatened, restoring wetlands and limiting urban expansion are crucial measures needed to protect this historically and ecologically important plant.</p>";
var cartona3 = "<p>Carthamus tinctorius (Safflower) <br><br> Carthamus tinctorius, or safflower, is a drought-resistant plant that thrives in Egypt’s arid and semi-arid regions, particularly in the Eastern and Western deserts and Upper Egypt. It grows best in dry, sandy, or light clay soils, preferring areas with low rainfall and high temperatures. This herbaceous plant, which can reach heights of up to 150 cm, is recognized by its bright yellow or orange flowers that grow in dense clusters. Historically, safflower was used in ancient Egypt to extract red and orange dyes for coloring fabrics, leather, and other materials.Today, safflower is primarily cultivated for its seeds, which are used to produce oil rich in unsaturated fatty acids. Safflower oil is considered a healthy cooking option and is also used in cosmetics. The flowers continue to be used as natural dyes, and in traditional medicine, safflower is believed to improve circulation and reduce inflammation. Although Carthamus tinctorius is not endangered, it faces threats from drought and climate change, particularly in agricultural regions of Asia and Africa. Sustainable farming practices and efficient irrigation techniques are necessary to ensure its continued cultivation.</p>";
var cartona4 = "<p>Eucalyptus camaldulensis (Camphor Tree) <br><br> Although the Eucalyptus camaldulensis, or camphor tree, is native to Australia, it has been widely introduced to Egypt, adapting well to the local conditions and becoming an important part of the natural landscape, particularly in Nile oases. This tree thrives in dry and temperate climates and requires a lot of light and direct sunlight. It can survive in nutrient-poor soils and even desert environments where rainfall is scarce. Known for its tall stature, reaching heights of up to 40 meters, the camphor tree’s narrow leaves have a distinctive strong scent due to the essential oils they contain, which are widely used in pharmaceutical industries.Historically, Eucalyptus camaldulensis has been valued for its medicinal properties, particularly for treating respiratory issues such as coughs and congestion. The oils extracted from its leaves are also used to relieve pain and treat wounds and inflammation. Aside from its medicinal uses, camphor plays a vital ecological role in preventing the formation of swamps by absorbing large amounts of water, thereby improving soil quality. Its wood is commonly used in construction and furniture-making. Although the tree is not endangered, conservation efforts focus on ensuring its continued role in soil stabilization and preventing overexploitation in regions with rapid urban growth.</p>";
var cartona5 = "<p>Ficus sycomorus (Sycamore Fig) <br><br> The Ficus sycomorus, or sycamore fig, has long been a crucial species in Egypt’s ecological and cultural history, serving as both a keystone species in semi-arid ecosystems and a symbol in ancient Egyptian civilization. This large tree prefers mild to warm climates and thrives in fertile, moist soils with ample sunlight. It is commonly found in the Nile Delta and southern Egypt, extending to other areas in Africa and the Middle East. The sycamore fig is known for its broad leaves and large size, often reaching heights of 20 meters or more. Its fruit, while smaller and less sweet than common figs, remains an important food source, especially in rural areas.The sycamore fig was highly regarded in ancient Egypt for both practical and symbolic reasons. Its wood was used to craft coffins, furniture, and boats, while its fruit was consumed by people and livestock alike. In ancient Egyptian mythology, the tree symbolized fertility and protection, and it was frequently depicted in tomb paintings and other forms of Pharaonic art. Additionally, it was associated with the goddess Hathor and believed to nourish the deceased in the afterlife. Although Ficus sycomorus is not currently endangered, its habitats in wetland areas of Egypt and Sudan are increasingly at risk due to deforestation, tree cutting, and rising temperatures. Protecting natural habitats and promoting sustainable land use are essential for preserving this culturally and ecologically important species.</p>";
var cartona6 = "<p>Egyptian Arum (Arum cyrenaicum) <br><br> The Egyptian Arum is a rare and distinctive plant found in Egypt’s semi-arid coastal regions, particularly around Marsa Matruh and Sidi Barrani. Recognizable by its large, arrow-shaped leaves and spathe, the plant is adapted to survive in coastal sand dunes and rocky outcrops. However, urban expansion and agricultural development have significantly reduced the Egyptian Arum’s natural habitat, making it increasingly rare in the wild. The plant is also susceptible to pests like snails, slugs, and fungal infections, which damage its leaves and roots, further weakening its ability to survive.The Egyptian Arum is classified as Endangered in Egypt, and current conservation efforts focus on habitat protection and pest management. By protecting the coastal ecosystems where the plant grows and controlling pest populations, conservationists aim to prevent further declines. Education programs in local communities raise awareness about the importance of preserving this plant and its natural habitat. Additionally, cultivation in botanical gardens is promoted to reduce pressure on wild populations.</p>";
var cartona7 = "<p>Carthamus oxyacantha (Wild Safflower) <br><br> Carthamus oxyacantha, or wild safflower, is a hardy, drought-tolerant plant that thrives in the dry, desert environments of Egypt, including regions such as Sinai and northwestern Egypt. It grows best in sandy soils with good drainage and can tolerate high temperatures and low rainfall. Wild safflower is a spiny shrub that can reach a height of about 1 meter, featuring yellow or orange flowers and small thorns that protect it from herbivores.In ancient Egypt, wild safflower was used to extract natural dyes for coloring fabrics, paper, and paintings. Its seeds produce oil similar to that of cultivated safflower, though it is less commonly harvested for commercial use. The plant is also valued in traditional medicine, where its flowers are used to treat digestive issues and joint inflammation. While Carthamus oxyacantha is not significantly endangered, it faces threats from drought and climate change, particularly in the Middle East and North Africa. Conservation efforts that focus on appropriate agricultural practices and water conservation are crucial for protecting this species from environmental challenges.</p>";
var cartona8 = "<p>Lawsonia inermis (Henna Plant) <br><br> Lawsonia inermis, or the henna plant, has been used for centuries for its cosmetic and medicinal properties, playing an important role in Egyptian culture. Henna grows best in dry and warm environments, typically in desert and oasis regions of Upper Egypt, where it thrives in well-drained soils and can withstand temperatures of up to 45°C. This evergreen shrub can reach heights between 1 and 6 meters and features shiny dark green leaves and small flowers ranging from white to pink. Its leaves contain a natural pigment that is harvested for use in henna dye production.In ancient Egypt, henna was a symbol of beauty and purity, commonly used in body adornment during weddings and religious ceremonies. It was also a symbol of renewal and immortality in Pharaonic carvings and wall paintings. Aside from its decorative use, Lawsonia inermis has antibacterial and antifungal properties, making it valuable in traditional medicine for treating wounds, skin inflammations, and headaches. Despite its extensive use, the henna plant is not endangered, but it faces threats from habitat loss due to intensive agriculture. Protecting its natural habitats and promoting sustainable farming practices are necessary to preserve its cultural and medicinal uses.</p>";
var cartona9 = "<p>Acacia (Acacia nilotica & Acacia seyal) <br><br> Acacia trees are an iconic feature of Egypt's Eastern Desert, Western Desert, and parts of the Sinai Peninsula, where they have long thrived in arid climates. These trees are critical for stabilizing soils, providing shade, and supporting local ecosystems by offering food and shelter to various animals. However, their populations have been steadily declining due to several threats. Desertification, the process by which fertile land becomes desert, is driven by climate change and poor land management, making the environment less hospitable for Acacia. Overgrazing by livestock, particularly goats and camels, has compounded the issue, preventing young trees from growing. In addition to environmental degradation, gall insects, termites, and wood borers attack Acacia trees, further weakening their structures and inhibiting their natural regeneration process.Acacia species are considered Near Threatened, and some subspecies face a higher risk of extinction without intervention. Protection measures include reforestation projects, where Acacia trees are planted in degraded areas to restore the land. Community-based conservation programs involve local communities in protecting the trees by promoting sustainable grazing practices. These efforts also focus on sustainable harvesting of Acacia for timber and medicinal uses, ensuring that the trees can recover and continue to thrive. As desertification worsens due to climate change, it is increasingly important to scale up these conservation efforts to protect Acacia populations.</p>";
var cartona10 = "<p>Desert Rose (Adenium obesum) <br><br> The Desert Rose is a stunning plant known for its striking pink, red, or white flowers and its ability to survive in Egypt’s Eastern Desert and Sinai Peninsula. It has become a popular ornamental plant worldwide, which has unfortunately led to its overexploitation in the wild. Illegal collection for the global plant trade is one of the primary threats facing the Desert Rose. In addition to human threats, the plant is vulnerable to pests such as spider mites, mealybugs, and aphids, which feed on its leaves and stems, causing damage that weakens the plant.Prolonged periods of drought, increasing temperatures, and habitat destruction due to urban expansion in desert regions further threaten this species. To protect the Desert Rose, conservationists are working to control illegal harvesting through legislation and trade monitoring. Efforts to grow the Desert Rose in botanical gardens and plant nurseries have also been encouraged, reducing the pressure on wild populations. Classified as Vulnerable, the Desert Rose requires continued protection to ensure its survival in both natural habitats and cultivated settings. Public awareness campaigns have been launched to educate people about the plant's ecological importance and discourage illegal trade.</p>";
var cartona11 = "<p>Phoenix dactylifera (Date Palm) <br><br> The Phoenix dactylifera, or date palm, is a crucial species in Egypt’s agricultural and economic landscape, particularly in desert and arid environments. The date palm thrives in hot, dry climates and grows best in sandy or gravelly soils that provide good drainage. It requires high temperatures to produce its energy-rich fruit, dates, and can be found predominantly in desert oases and along the Nile valleys. The tree’s tall trunk can reach heights of up to 30 meters, and its long, drooping leaves create a distinct silhouette in the arid landscape.Dates have been a fundamental food source in Egypt and other Arab countries for centuries, rich in sugars, vitamins, and minerals, making them a staple food in harsh desert conditions. Economically, date farming remains an essential agricultural activity in Egypt, with the fruit being a major export product. In addition to food, the date palm is also valued for its wood, which is used in construction, and its leaves, which are woven into baskets, ropes, and other materials. Despite the economic and cultural importance of the date palm, it faces challenges from drought, climate change, and plant diseases, particularly in desert regions of North Africa and the Middle East. To safeguard its future, it is necessary to conserve water, use modern agricultural techniques, and improve disease resistance.</p>";
var cartona12 = "<p>Malva parviflora (Small-flowered Mallow) <br><br> Malva parviflora, commonly known as the small-flowered mallow, is a versatile and hardy plant that can thrive in a range of environments, including agricultural regions and garden areas in Egypt. It grows best in nutrient-rich, moist soils but can adapt to somewhat dry conditions. The plant is commonly found near the Nile Basin, where it grows quickly and forms dense mats of round leaves and small, pale pink flowers. Reaching a height of about 50 cm, Malva parviflora is known for its rapid growth and ability to adapt to varying climates.Traditionally, mallow has been used in folk medicine to treat respiratory issues such as coughs and throat infections, as well as digestive problems. It is also valued for its anti-inflammatory and antioxidant properties, making it a popular natural remedy. In addition to its medicinal uses, mallow leaves and seeds are used in cooking, providing a rich source of vitamins and minerals such as Vitamin C, Vitamin A, and calcium. While Malva parviflora is not endangered, protecting natural environments from pollution and avoiding the use of harmful chemicals in surrounding areas is necessary for maintaining its ecological and health benefits.</p>";
var cartona13 = "Jujube (Ziziphus spina-christi) <br><br> Jujube, or Christ’s Thorn, is an ancient tree with a rich history in Egypt, known for its nutritious fruit and medicinal uses. Found in desert oases like Siwa and along the Nile Valley, the Jujube tree has long been valued for its resilience in arid environments. However, the increasing pressures of urbanization and agricultural expansion have significantly reduced its natural habitat. The overharvesting of Jujube for its fruit and timber has further exacerbated this decline. Scale insects, fruit flies, and borer insects present additional threats, damaging the fruit and tree structure, which reduces yields and weakens the trees.The Jujube tree is currently classified as Near Threatened, and conservation efforts focus on sustainable harvesting practices to balance the tree’s ecological and economic importance. Replanting programs in degraded oases aim to restore Jujube populations, and some initiatives encourage the integration of Jujube into agroforestry systems, where it can provide shade, prevent erosion, and contribute to biodiversity while offering economic benefits to local communities. Addressing these threats is vital to preserving the Jujube tree’s cultural and environmental legacy.";
var cartona14 = "<p>Moringa (Moringa peregrina) <br><br> Moringa, often referred to as the “miracle tree,” is highly valued for its nutritional and medicinal properties. It grows in Egypt’s Sinai Peninsula and Eastern Desert, where it provides numerous benefits to local communities and ecosystems. However, overharvesting for Moringa leaves, seeds, and oil has placed enormous pressure on wild populations. Aphids, leaf miners, and stem borers are the primary pests threatening Moringa trees, causing damage that reduces their leaf production and weakens the overall health of the tree.In addition to overharvesting, Moringa is threatened by desertification and habitat loss caused by overgrazing, climate change, and urban expansion. Classified as Vulnerable, Moringa requires targeted conservation efforts, including reforestation programs and the promotion of sustainable harvesting practices. Some initiatives focus on integrating Moringa into agricultural systems as a drought-resistant crop, which can provide both environmental benefits (such as preventing soil erosion) and economic opportunities for local communities. These efforts are crucial in ensuring the long-term survival of this valuable species.</p>";
var cartona15 = "<p>Sahara Mustard (Brassica tournefortii) <br><br> Sahara Mustard is a drought-resistant plant found mainly in Egypt’s Western Desert and the Sinai Peninsula. It plays an important role in stabilizing sand dunes and preventing soil erosion, making it a vital component of desert ecosystems. However, Sahara Mustard populations have been steadily declining due to the encroachment of invasive species, which compete for limited resources and outcompete native plants. The plant is also vulnerable to pests like leaf miners, aphids, and caterpillars, which weaken its structure and reduce its ability to grow and reproduce.Although Sahara Mustard is not currently classified as endangered, it is considered At Risk due to habitat destruction caused by agricultural expansion and urbanization. Conservation efforts focus on controlling invasive species, restoring native vegetation, and protecting natural desert habitats where Sahara Mustard thrives. By preventing further habitat loss and managing pest populations, conservationists hope to stabilize and increase Sahara Mustard populations, ensuring the long-term health of desert ecosystems.</p>";
var cartona16 = "<p>Salvadora persica (Toothbrush Tree) <br><br> Salvadora persica, or the toothbrush tree, has been used for centuries as a natural method of maintaining oral hygiene in regions such as Egypt, Africa, the Middle East, and the Indian subcontinent. This tree grows in hot, dry climates, often in desert areas such as Sinai and the Bahariya Oasis in Egypt. The toothbrush tree thrives in sandy or clay soils and can withstand high temperatures. It is easily recognizable by its smooth green leaves and small white flowers, but it is best known for its roots, which are used to make miswak—a traditional tool for cleaning teeth.The miswak from the Salvadora persica tree contains natural compounds that aid in teeth cleaning, with antibacterial and antifungal properties. In addition to its oral health benefits, the tree has long been used in traditional medicine to treat skin inflammations and wounds. Miswak continues to hold significant cultural importance in many Islamic societies, where it is used as an alternative to modern toothpaste. Although Salvadora persica is not globally endangered, its natural habitats in desert regions are at risk from degradation, overgrazing, and drought. Protecting these habitats and promoting sustainable cultivation practices are essential for preserving this ecologically and culturally important tree.</p>";
var cartona17 = "<p>Tamarisk (Tamarix aphylla) <br><br> Tamarisk trees, known for their resilience in harsh environments, are found along the Nile River, desert oases, and Egypt’s Western Desert. These trees play a vital role in preventing soil erosion, particularly in arid and semi-arid environments. They help stabilize desert dunes and prevent the encroachment of sands into cultivated areas. However, Tamarisk populations are declining due to habitat destruction driven by changes in water management systems along the Nile, such as the construction of dams and irrigation projects. These developments have altered the flow of water, reducing the moisture available to Tamarisk trees and leading to a reduction in their natural habitat.Biological threats include infestations from the Tamarisk leaf beetle, which causes significant defoliation, and aphids, which weaken the tree and reduce its capacity to thrive. In addition, firewood collection and urban expansion in desert regions have further reduced Tamarisk numbers. Classified as Moderately Threatened, Tamarisk conservation efforts focus on riparian zone restoration along the Nile and other water bodies, as well as the implementation of biological control methods to manage pest populations. Some initiatives encourage locals to plant Tamarisk trees to restore degraded ecosystems and improve land productivity.</p>";
function arti1() {
    document.getElementById('artiAp').innerHTML = cartona;
}
function arti2() {
    document.getElementById('artiAp').innerHTML = cartona2;
}
function arti3() {
    document.getElementById('artiAp').innerHTML = cartona3;
}
function arti4() {
    document.getElementById('artiAp').innerHTML = cartona4;
}
function arti5() {
    document.getElementById('artiAp').innerHTML = cartona5;
}
function arti6() {
    document.getElementById('artiAp').innerHTML = cartona6;
}
function arti7() {
    document.getElementById('artiAp').innerHTML = cartona7;
}
function arti8() {
    document.getElementById('artiAp').innerHTML = cartona8;
}
function arti9() {
    document.getElementById('artiAp').innerHTML = cartona9;
}
function arti10() {
    document.getElementById('artiAp').innerHTML = cartona10;
}
function arti11() {
    document.getElementById('artiAp').innerHTML = cartona11;
}
function arti12() {
    document.getElementById('artiAp').innerHTML = cartona12;
}
function arti13() {
    document.getElementById('artiAp').innerHTML = cartona13;
}
function arti14() {
    document.getElementById('artiAp').innerHTML = cartona14;
}
function arti15() {
    document.getElementById('artiAp').innerHTML = cartona15;
}
function arti16() {
    document.getElementById('artiAp').innerHTML = cartona16;
}
function arti17() {
    document.getElementById('artiAp').innerHTML = cartona17;
}